[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'

# colorscheme
[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

# git
[[plugins]]
repo = 'airblade/vim-gitgutter'

